project:
  type: website

website:
  title: "Atelier tvCoef"
  navbar:
    left:
      - href: index.qmd
        text: Slides
      - href: manuel_installation.qmd
        text: Manuel d'installation
      - href: index.qmd
        text: TP
  page-footer:
    left: "Copyright 2023, Claire de Rosamel, Alain Quartier-la-Tente, Insee"

format:
  html:
    theme: Litera
    toc: true

lang: fr
language:
 title-block-author-plural: Auteurs
 title-block-published: Date

execute:
  freeze: auto
