project:
  type: website

website:
  title: "Atelier tvCoef"
  navbar:
    left:
      - href: slides.qmd
        text: Slides
      - href: manuel_installation.qmd
        text: Manuel d'installation
      - href: TP.qmd
        text: TP
  page-footer:
    left: "Copyright 2023, Claire de Rosamel, Alain Quartier-la-Tente, Insee"

format:
  html:
    theme: Litera
    toc: true

lang: fr
language:
 title-block-author-plural: Auteurs
 title-block-published: Date

execute:
  freeze: auto


# giscus
comments:
  giscus:
    repo: AQLT/AteliertvCoef
    repo-id: "R_kgDOJHHw_w"
    category: "Announcements"
    category-id: "DIC_kwDOIepag84CSt5_"
    mapping: "pathname"
    language: fr
    #strict: false
    reactions-enabled: true
    loading: lazy
    #emit-metada: false
    input-position: "bottom"
    theme: "light"
    #crossorigin: "anonymous"
