on:
  workflow_dispatch:
  push:
    branches: master

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# giscus
comments:
  giscus:
    repo: AQLT/AteliertvCoef
    repo-id: "R_kgDOJHHw_w"
    category: "Announcements"
    category-id: "DIC_kwDOIepag84CSt5_"
    mapping: "pathname"
    language: fr
    #strict: false
    reactions-enabled: true
    loading: lazy
    #emit-metada: false
    input-position: "bottom"
    theme: "light"
    #crossorigin: "anonymous"
